package Generic.Generic_641_642_643_644;

public enum Watercolors {
    ZINC,LINON_YELLOW,MEIUM_YELLOW,DEEP_YELLOW,ORANGE,BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,COBALT_BLUE_HUE,PERMANENT_GREEN,
    VIRIDIA_HUE
    ,CERULEAN_BLUE_HUE,SAP_GREEN,YELLOW_OCHER,BURNT_SIENNA,RAW_UMBER,BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK


}
